dt = read_csv("./data/typhoon_twit.csv")
dt_E = read_csv("./data/earthquakes_twit.csv")
dt_W = read_csv("./data/winter_twit.csv")
dt_Thun = read_csv("./data/thunder_twit.csv")
dt_F = read_csv("./data/fire_twit.csv")